# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4725f86006ab58237f26cf57412901a2ee051e1edd6f552096d2c3713a4d3b84e5218cdf483f7dbf70c1444ac1981563cfc9102b5f88ea5ffc76420394157cfa

test:
  secret_key_base: 60d17d495223489e30d4cdf2fb5df64cc2c48e4fb57938ab8902971f3fc3740ac7e65ccf822b90b263fe78b70e1907e03efe6ead9e75fc4b4f528a41210fa1a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
